import Head from 'next/head'
import Header from '../components/Header'
import Nav from '../components/Nav'
import Results from '../components/Results'
import requests from '../utils/requests'

export default function Home(props) {
  console.log(props)
  return (
    <div>
      <Head>
        <title>Hulu 2.0</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    <Header />

    {/* Header Component */}
    {/* Nav Component */}

    <Nav />
    <Results />
    {/* Results Component */}
    </div>
  )
}

//this gets rendered first (server)
export async function getServerSideProps(context) {
  const genre = context.query.genre;
  const request = await fetch(`https://api.themoviedb.org/3${requests[genre]?.url || requests.fetchTrending.url}`
  ).then(response => response.json());
  return {
    props: {
      request: request.results,
    }
}
}